In [1]:
import numpy as np

In [2]:
arr = np.array([1,56,34,78,2])

In [3]:
arr, type(arr)

(array([ 1, 56, 34, 78,  2]), numpy.ndarray)

In [4]:
arr.shape

(5,)

In [5]:
arr.size #Number of elements in the array.

5

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.itemsize

8

In [8]:
arr1 = np.array([12.3,123])

In [9]:
arr1, arr1.dtype

(array([ 12.3, 123. ]), dtype('float64'))

In [10]:
arr1.itemsize

8

In [11]:
arr1 = np.array(['cdac',123])

In [12]:
arr1, arr1.dtype

(array(['cdac', '123'], dtype='<U21'), dtype('<U21'))

In [13]:
arr1.itemsize

84

In [14]:
arr2d = np.array([[1,2],[3,4]]) #Number of elements in the array.

In [15]:
arr2d.shape, arr2d.size, arr2d.dtype, arr2d.itemsize

((2, 2), 4, dtype('int64'), 8)

In [16]:
arr2d = np.array([[1,2],[3,4],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [18]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [19]:
arr3d.shape, arr3d.size, arr3d.dtype,arr3d.itemsize

((2, 2, 2), 8, dtype('int64'), 8)

In [20]:
arr = np.array([1,2,3],dtype='int8')

In [21]:
arr.dtype

dtype('int8')

In [22]:
arrComplex = np.array([1,2,3],dtype='complex')

In [23]:
arrComplex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [24]:
arrComplex.dtype, arrComplex.itemsize

(dtype('complex128'), 16)

In [25]:
np.zeros((2,22))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [26]:
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [29]:
arr3d_zeros = np.zeros(arr3d.shape)

In [30]:
arr3d_zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
np.empty((2,2,2,3),dtype='int')

array([[[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0]]]])

# arange()

In [32]:
myRange = np.arange(1,100,2)

In [33]:
myRange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [34]:
myRange = np.arange(np.pi,np.pi*10,1)

In [35]:
myRange

array([ 3.14159265,  4.14159265,  5.14159265,  6.14159265,  7.14159265,
        8.14159265,  9.14159265, 10.14159265, 11.14159265, 12.14159265,
       13.14159265, 14.14159265, 15.14159265, 16.14159265, 17.14159265,
       18.14159265, 19.14159265, 20.14159265, 21.14159265, 22.14159265,
       23.14159265, 24.14159265, 25.14159265, 26.14159265, 27.14159265,
       28.14159265, 29.14159265, 30.14159265, 31.14159265])

In [36]:
myRange = np.arange(0.5,7.7,0.2)

In [37]:
myRange

array([0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9,
       3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5,
       5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5])

In [38]:
myRange = np.arange(np.pi,10*np.pi,np.pi)

In [39]:
myRange

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061, 15.70796327,
       18.84955592, 21.99114858, 25.13274123, 28.27433388])

# Special case if step is having rounding off error

In [40]:
myRange = np.arange(0.5,1.9,0.7)

In [41]:
myRange

array([0.5, 1.2])

In [42]:
myRange = np.arange(0,4.9,0.7)

In [43]:
myRange

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9])

# linearly spaced values

In [44]:
np.linspace(0,1,5) # create n-1 parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.linspace(0,20,5) # create n-1 parts

array([ 0.,  5., 10., 15., 20.])

# Arithmetic Operation

In [46]:
arr1=np.array([100,345,678,3456])
arr2=np.array([12,15,78,90])

In [47]:
arr1+ arr2

array([ 112,  360,  756, 3546])

In [48]:
arr1 -  arr2

array([  88,  330,  600, 3366])

In [49]:
arr1 * arr2

array([  1200,   5175,  52884, 311040])

In [50]:
arr1 * 100

array([ 10000,  34500,  67800, 345600])

In [51]:
arr1 / 40 * 89 + arr2 * 10 + 100

array([ 442.5  , 1017.625, 2388.55 , 8689.6  ])

# exercise


In [52]:
m1=np.array([78,98,85])
m2=np.array([96,77,80])
m3=np.array([99,91,78])

In [53]:
# find percentage of every student

# create 2d array for all records and perform
#sum(), sum(axis=0), sum(axis=1)

# Create array of random numbers

repeatition is allowed

In [54]:
r_arr = np.random.randint(0,1000,(4,5))
#Return random integers from low (inclusive) to high (exclusive).

In [55]:
r_arr

array([[306, 295, 143, 900, 565],
       [906, 366, 348, 828, 337],
       [319, 496, 687, 142, 971],
       [ 17, 625, 495, 301, 747]])

In [56]:
r_arr = np.random.randint(0,5,(4,5))

In [57]:
r_arr

array([[0, 4, 0, 4, 2],
       [1, 2, 3, 4, 3],
       [0, 3, 3, 3, 2],
       [4, 1, 2, 0, 3]])

In [58]:
r_arr = np.random.rand(10)

In [59]:
r_arr

array([0.95948494, 0.50911479, 0.74339531, 0.76791604, 0.98140056,
       0.70147749, 0.09585679, 0.23424991, 0.55549106, 0.29628778])

In [60]:
r_arr = np.random.rand(10,2)

In [61]:
r_arr

array([[0.45616981, 0.74700932],
       [0.27143167, 0.94121987],
       [0.7163399 , 0.40955792],
       [0.41993762, 0.05593118],
       [0.74087528, 0.03939412],
       [0.49189889, 0.12480426],
       [0.39704347, 0.77890836],
       [0.29469109, 0.75947212],
       [0.40205468, 0.59533749],
       [0.3072384 , 0.70351795]])

# Matrix Operations

In [62]:
A = np.array([[1,2],[3,4]])

In [63]:
B = np.array([[100,200],[300,400]])

In [64]:
A*B # element wise multiplication

array([[ 100,  400],
       [ 900, 1600]])

In [65]:
A@B

array([[ 700, 1000],
       [1500, 2200]])

In [66]:
A.dot(B)

array([[ 700, 1000],
       [1500, 2200]])

# Universal Functions

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

In [67]:
A = np.array([[1,2],[3,4]])

In [68]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [69]:
np.power(A,2)

array([[ 1,  4],
       [ 9, 16]])

In [70]:
np.sin(A)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [71]:
np.cos(A)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

# Numpy special representations for floating point values

+inf    -> + infinity

-inf    -> - infinity

nan     -> Not a Number



# ravel

In [72]:
r_arr = np.random.randint(0,1000,(2,2,2))

In [73]:
for elem in r_arr:
    print("Element in array is : ")
    print(elem)

Element in array is : 
[[886 317]
 [ 46  41]]
Element in array is : 
[[441 509]
 [600 676]]


In [74]:
for elem in r_arr.ravel():
    print("Element in array is : ")
    print(elem)

Element in array is : 
886
Element in array is : 
317
Element in array is : 
46
Element in array is : 
41
Element in array is : 
441
Element in array is : 
509
Element in array is : 
600
Element in array is : 
676


# concat

In [75]:
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6]])

In [76]:
x

array([[1, 2],
       [3, 4]])

In [77]:
y

array([[5, 6]])

In [78]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
np.concatenate((x, y), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

# add new axis

In [80]:
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [81]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [82]:
col_vector = a[:,np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

# vectorized conditions

In [83]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a<5)
print(a[a<5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[1 2 3 4]


# vstack and hstack

In [84]:
a1 = np.array([[1, 1],

               [2, 2]])

a2 = np.array([[3, 3],

               [4, 4]])

In [85]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [86]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# reverse an array

In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

# Create a neuron in numpy

fun neuron has two parameters

x : input array ( size n)

w : weights (size n)

bias : its a single value / constant

x & w are of same size

Step1 : calculate their element wise multiplication

Step2 : calculate sum of above multiplication and add bias to it

Step3 : return the value



In [88]:
def neuron(x,w,bias):
    X = x*w
    X = X.sum() + bias
    return X

In [89]:
x= np.array([10,20,30])

In [90]:
w=np.random.rand(x.shape[0])

In [91]:
w

array([0.94153174, 0.27430116, 0.26999453])

In [92]:
bias = 100

In [93]:
neuron(x,w,bias)

np.float64(123.00117659740832)